### PR TITLE
LC0005 Avoid duplicate diagnostic, add diagnostic field syntax length

### LINKED ISSUE #248: LC0005 field datatype with length
Incorrectly cased field data types with length e.g. text[10] will not give LC0005 warning.

        field(2; Subject; text[10])
        {
            DataClassification = CustomerContent;
        }
        field(3; Body; coDe[10])
        {
            DataClassification = CustomerContent;
        }

### LINKED ISSUE #639: LC0005 Duplicate diagnostic for unlimited texts
For texts a duplicate LC0005 diagnostic is raised when not specifying a range expression (so unlimited length):
```
codeunit 50100 MyCodeunit
{
    var
        mytext: TeXt; // duplicate diagnostic here
        mytext2: TeXt[10]; // only one diagnostic here
}
```
LC0005

### PR DESCRIPTION
**Pull request by ans-bar-bm**
Fixes #248 
Fixes #639 

- Avoids duplicate diagnostics from `LengthDataType` and `SimpleTypeReference` when no range expression is set (`Text` with unlimited length).
- Adds diagnostic when `LengthDataType` range expression is set and no `SimpleTypeReference` parent syntax node is present (table field definitions).

### CODE REVIEW

**Comment by Arthurvdv** [comment]
Thank you for contributing and creating an pull-request for the both issues.

I've recently started on refactoring this rule to improve it and simultaneously reduce the complexity. The idea is to eventually remove the need for the generic AnalyseNodes method and have a method for specific SyntaxKinds. So I have a slight preference to add this to a separate method instead of extending the generic AnalyseNodes method.

If hope you don't mind I'll added an commit on this PR to move your improvement to a separate method: AnalyzeLengthDataType

Could you have a look at this and provide feedback if you're okay with these changes?

**Comment by ans-bar-bm** [comment]
Sure i don't mind, it does make sense to split it up.
I've had a quick test, but it seems `AnalyzeLengthDataType` is never triggered for me. Unfortunatly i don't really know why that could be. Here's my test snippet:
```
table 50100 MyTable
{
    fields
    {
        field(1; Test; TeXT[10]) { }
    }

    var
        x: TeXT[100];
        y: TeXT;
}
```
Currently i only get a diagnostic on the y variable (and not on x and the Test field), and that one seems to come from AnalyseNodes as skipping with `continue` doesn't seem to work.
At this point i am kind of doubting myself tho since i did a very simple `IsKind(...)` check while debugging at that also failed despite the debugger showing me the right `SyntaxKind`...
Maybe you could check if the test works for you?

**Comment by Arthurvdv** [comment]
I've did some more testing, unfortunately I can't seem to reproduce the same results as you are experiencing. The sample you provided all three instances get's flagged by the 0005 rule it seems. Currently I have no idea why this isn't working for you.

image

**Comment by ans-bar-bm** [comment]
It's very likely i have just screwed something up on my end then.
Thanks for taking a look / refactoring the changes; let me know if there is anything else left for me to do.

**Comment by Arthurvdv** [comment]
@ans-bar-bm No problem! Again thank you for proving the PR, this was of a great help to determine the logic to prevent the duplicate diagnostic.

**Pull request merged**
