### PR TITLE
Add new rule LC0021 Confirm() must be implemented through the "Confirm Management" codeunit

### PR DESCRIPTION
**Pull request by Arthurvdv**
image

I've created a new rule LC0021: Confirm() must be implemented through the "Confirm Management" codeunit from the System Application.

Based on the discussion here: https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/205.

If there's anything missing or incorrect, please let me know and I'll try to fix it.

### CODE REVIEW

**Comment by StefanMaron** [comment]
looks very good :)

just one thing, I did not test this but I would expect this info to trigger as well if you create a Confirm procedure yourself in a codeunit forexample and call that procedure.

Maybe you can check if thats the case, and see if there would be a way to avoid this.

**Comment by Arthurvdv** [comment]
Good catch! Indeed creating a codeunit with a Confirm() procedure inside it, then this rule is shown unjustified.

Schermafbeelding 2022-10-16 om 09 50 23

I'm going to search and try and fine a way to avoid this.

**Comment by StefanMaron** [comment]
Have a look now, this should work. 
You almost had it ;)

**Comment by Arthurvdv** [comment]
Yes!!
image

The variable windows from the debugger has set me on the wrong feet it seems :-D
Thank you for making time, on such a short notice, to help me with this, really appreciated!

Two small questions;
* Can I close/link the discussion to this PR somehow?
* Do I need to add this new rule to the wiki? In case a user clicks on the warning from VS Code it would be nice to land on correct page with the explanation.

**Comment by StefanMaron** [comment]
Am not sure if you can create the wiki page yourself, but there shoud be a wiki page for sure.
For the discussion I used a label, because github does not support closing them yet

**Pull request merged**
